name: 学生助理考勤

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '* * * * *'

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Attendance
        run: python3 test.py
      - name: idonot
        run: echo "hello, world"
