name: 学生助理考勤

on:
  push:
  schedule:
    - cron: '30 0,6 * * *'
  watch:
    types: started

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Attendance
        run: python attendance.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} ${{ secrets.ATTENDANCE_TIME }}
